# Generated by Django 2.0.2 on 2018-02-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('bathi', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d')),
                ('outi', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d')),
                ('cousinei', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d')),
                ('floori', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d')),
                ('fireplacei', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d')),
                ('stairsi', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d')),
                ('arti', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='WorkModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('material_type', models.CharField(choices=[('marble', 'Μάρμαρο'), ('granite', 'Γρανίτης'), ('quartz', 'Χαλαζιακά')], max_length=10)),
                ('place_type', models.CharField(choices=[('bath', 'Μπάνια'), ('out', 'Εξωτερικοί χώροι'), ('cousines', 'Κουζίνες'), ('floor', 'Πάτωμα'), ('fireplace', 'Τζάκια'), ('stairs', 'Σκάλες'), ('art', 'Καλλιτεχνίματα')], max_length=28)),
                ('image1', models.ImageField(upload_to='images/%Y/%m/%d')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
