# Generated by Django 2.0.2 on 2018-02-13 15:01

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='thumbnail',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='static/thumbnails/', verbose_name='thumbnail'),
        ),
    ]
