# Generated by Django 2.0.2 on 2018-02-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indexmodel',
            old_name='arti',
            new_name='art',
        ),
        migrations.RenameField(
            model_name='indexmodel',
            old_name='bathi',
            new_name='bath',
        ),
        migrations.RenameField(
            model_name='indexmodel',
            old_name='cousinei',
            new_name='cousine',
        ),
        migrations.RenameField(
            model_name='indexmodel',
            old_name='fireplacei',
            new_name='fireplace',
        ),
        migrations.RenameField(
            model_name='indexmodel',
            old_name='floori',
            new_name='floor',
        ),
        migrations.RenameField(
            model_name='indexmodel',
            old_name='outi',
            new_name='out',
        ),
        migrations.RenameField(
            model_name='indexmodel',
            old_name='stairsi',
            new_name='stairs',
        ),
        migrations.AlterField(
            model_name='indexmodel',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
