# Generated by Django 2.0.2 on 2018-02-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20180225_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='workmodel',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='workmodel',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='workmodel',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d'),
        ),
    ]
