# Generated by Django 2.0.2 on 2018-02-13 17:41

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_imagemodel_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='thumbnail',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='static/thumbnails/', verbose_name='thumbnail'),
        ),
    ]
