# Generated by Django 2.0.2 on 2018-02-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_auto_20180225_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhereModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d')),
            ],
        ),
    ]
