# Generated by Django 2.0.2 on 2018-02-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_auto_20180213_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workmodel',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
