# Generated by Django 2.0.2 on 2018-02-15 17:12

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_auto_20180215_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='name',
        ),
        migrations.AddField(
            model_name='workmodel',
            name='image1',
            field=models.ImageField(null=True, upload_to='static/images'),
        ),
        migrations.AddField(
            model_name='workmodel',
            name='image2',
            field=models.ImageField(null=True, upload_to='static/images'),
        ),
        migrations.AddField(
            model_name='workmodel',
            name='image3',
            field=models.ImageField(null=True, upload_to='static/images'),
        ),
        migrations.AddField(
            model_name='workmodel',
            name='thumbnail',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='static/thumbnails/', verbose_name='thumbnail'),
        ),
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
