# Generated by Django 2.0.2 on 2018-02-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_auto_20180215_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workmodel',
            name='image1',
            field=models.ImageField(blank=True, upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='workmodel',
            name='image2',
            field=models.ImageField(blank=True, upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='workmodel',
            name='image3',
            field=models.ImageField(blank=True, upload_to='static/images'),
        ),
    ]
