# Generated by Django 2.0.2 on 2018-02-17 14:10

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_auto_20180216_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workmodel',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='workmodel',
            name='image3',
        ),
        migrations.AlterField(
            model_name='workmodel',
            name='image1',
            field=models.ImageField(upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='workmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='workmodel',
            name='thumbnail',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='static/thumbnails/', verbose_name='thumbnail'),
        ),
    ]
