# Generated by Django 2.0.2 on 2018-02-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_auto_20180217_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workmodel',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='workmodel',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
