# Generated by Django 2.0.2 on 2018-02-17 14:38

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_auto_20180217_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='workmodel',
            name='thumbnail',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='static/thumbnails/', verbose_name='thumbnail'),
        ),
    ]
