# Generated by Django 2.0.2 on 2018-02-18 13:50

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0010_auto_20180217_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='workmodel',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='workmodel',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='workmodel',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='workmodel',
            name='thumbnail',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='thumbanail/%Y/%m/%d'),
        ),
    ]
