# Generated by Django 2.0.2 on 2018-02-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0011_auto_20180218_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workmodel',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='workmodel',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workmodel',
            name='image1',
            field=models.ImageField(upload_to='images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='workmodel',
            name='material_type',
            field=models.CharField(choices=[('marble', 'Μάρμαρο'), ('granite', 'Γρανίτης'), ('quartz', 'Χαλαζιακά')], max_length=10),
        ),
        migrations.AlterField(
            model_name='workmodel',
            name='place_type',
            field=models.CharField(choices=[('bath', 'Μπάνια'), ('out', 'Εξωτερικοί χώροι'), ('cousines', 'Κουζίνες'), ('floor', 'Πάτωμα'), ('fireplace', 'Τζάκια'), ('stairs', 'Σκάλες'), ('art', 'Καλλιτεχνίματα')], max_length=28),
        ),
    ]
