# Generated by Django 2.0.2 on 2018-02-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0012_auto_20180224_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bath', models.ImageField(upload_to='images/%Y/%m/%d')),
                ('out', models.ImageField(upload_to='images/%Y/%m/%d')),
                ('cousine', models.ImageField(upload_to='images/%Y/%m/%d')),
                ('floor', models.ImageField(upload_to='images/%Y/%m/%d')),
                ('fireplace', models.ImageField(upload_to='images/%Y/%m/%d')),
                ('stairs', models.ImageField(upload_to='images/%Y/%m/%d')),
                ('art', models.ImageField(upload_to='images/%Y/%m/%d')),
            ],
        ),
    ]
