# Generated by Django 2.0.2 on 2018-02-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0013_indexmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexmodel',
            name='name',
            field=models.CharField(default='index', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
